import Navbar from "@/components/Navbar";
import Main from "@/components/Main";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hilmyfe | Frontend Developer</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Navbar/>
      <Main/>
    </div>
  );
}
